/**
 * vapid:gen — print a fresh VAPID keypair for Web Push (push-notifications T2).
 *
 * The self-hoster runs `bun run vapid:gen` ONCE, then pastes the printed lines into their `.env`.
 * The keypair is the app-wide push application-server identity: the PRIVATE key stays server-side
 * (signs push payloads, never shipped to the browser), the PUBLIC key is the applicationServerKey the
 * browser needs. Rotating the keypair invalidates existing subscriptions (users re-subscribe) — only
 * do it deliberately.
 *
 * Pure stdout — reads nothing, writes nothing; safe to run anytime.
 */

import webpush from 'web-push';

const { publicKey, privateKey } = webpush.generateVAPIDKeys();

// biome-ignore lint/suspicious/noConsole: a CLI helper whose whole job is to print to stdout.
console.log(`# VAPID keypair for Web Push — generated by \`bun run vapid:gen\`.
# Paste these into backend/.env. Keep VAPID_PRIVATE_KEY secret (server-only, like SESSION_SECRET).
# Set VAPID_SUBJECT to a mailto: or https: contact the push service can reach.
VAPID_PUBLIC_KEY=${publicKey}
VAPID_PRIVATE_KEY=${privateKey}
VAPID_SUBJECT=mailto:you@example.com`);
