/**
 * Validation limits and constraints
 */
export const VALIDATION_LIMITS = {
  VEHICLE: {
    MAKE_MAX_LENGTH: 50,
    MODEL_MAX_LENGTH: 50,
    NICKNAME_MAX_LENGTH: 50,
    LICENSE_PLATE_MAX_LENGTH: 20,
    MIN_YEAR: 1900,
  },
  EXPENSE: {
    DESCRIPTION_MAX_LENGTH: 500,
    MAX_AMOUNT: 1_000_000,
    MAX_TAGS: 10,
    TAG_MAX_LENGTH: 50,
  },
  INSURANCE: {
    COMPANY_MAX_LENGTH: 100,
    POLICY_NUMBER_MAX_LENGTH: 50,
    MAX_TERM_MONTHS: 24,
  },
  FINANCING: {
    PROVIDER_MAX_LENGTH: 100,
    MAX_APR: 50,
    MAX_TERM_MONTHS: 600,
    MIN_DAY_OF_MONTH: 1,
    MAX_DAY_OF_MONTH: 31,
    MIN_DAY_OF_WEEK: 0,
    MAX_DAY_OF_WEEK: 6,
  },
  SETTINGS: {
    MAX_BACKUP_RETENTION: 100,
    MAX_SYNC_INACTIVITY_MINUTES: 30,
  },
} as const;
