/**
 * Theming engine — themes.css generator (spec T7, Phase 2). Emits the CSS that paints a NON-default theme
 * with zero FOUC and zero token duplication in JS: one `:root[data-theme="<id>"]` block (light variant) +
 * one `:root[data-theme="<id>"].dark` block (dark variant) per non-default registry theme.
 *
 * WHY default is excluded: app.css already declares the `default` palette in the bare `:root` / `.dark`
 * blocks (no `data-theme` attribute). So `data-theme` ABSENT (or `="default"`) renders today's look from
 * app.css; a non-default id adds a higher-specificity `:root[data-theme="x"]` override. Generating a
 * `default` block would just duplicate app.css (and risk drift) — the C185 registry≡app.css guard already
 * pins that pair. Hence the generator skips `default`.
 *
 * Pure string builder — no DOM, no fs. The checked-in `themes.css` is produced from this (a guard test
 * asserts the committed file covers exactly the non-default registry ids, so adding a theme to the
 * registry without regenerating trips it). `.dark` matches app.css's `@custom-variant dark (&:is(.dark *))`
 * convention: the dark override is `:root[data-theme="x"].dark`.
 */

import type { ThemeDefinition, ThemeTokens } from './theme-types';

const GENERATED_HEADER = `/* GENERATED by themes-css.ts (theming-engine T7). DO NOT EDIT BY HAND — regenerate from THEME_REGISTRY. */`;

/** Render one variant's token map as `\t--key: value;` declaration lines (sorted for stable output). */
function declarations(tokens: ThemeTokens): string {
  return Object.keys(tokens)
    .sort()
    .map((key) => `  --${key}: ${tokens[key as keyof ThemeTokens]};`)
    .join('\n');
}

/** The two CSS blocks (light + dark) for ONE non-default theme. */
export function themeBlocks(theme: ThemeDefinition): string {
  const sel = `:root[data-theme="${theme.id}"]`;
  return (
    `${sel} {\n${declarations(theme.light)}\n}\n\n` +
    // The dark override: this theme's dark palette applies when BOTH data-theme matches AND .dark is set.
    `${sel}.dark {\n${declarations(theme.dark)}\n}`
  );
}

/**
 * Generate the full `themes.css` body from the registry. `default` is excluded (app.css owns its bare
 * `:root`/`.dark`). Deterministic: themes sorted by id, so the output is stable across regenerations.
 */
export function generateThemesCss(
  registry: Record<string, ThemeDefinition>,
  defaultThemeId = 'default'
): string {
  const nonDefault = Object.values(registry)
    .filter((t) => t.id !== defaultThemeId)
    .sort((a, b) => a.id.localeCompare(b.id));

  if (nonDefault.length === 0) {
    return `${GENERATED_HEADER}\n/* No non-default themes registered yet — default is served by app.css's bare :root/.dark. */\n`;
  }
  return `${GENERATED_HEADER}\n\n${nonDefault.map(themeBlocks).join('\n\n')}\n`;
}

/** The non-default theme ids the generated css must cover (the guard's expected set). */
export function nonDefaultThemeIds(
  registry: Record<string, ThemeDefinition>,
  defaultThemeId = 'default'
): string[] {
  return Object.values(registry)
    .filter((t) => t.id !== defaultThemeId)
    .map((t) => t.id)
    .sort();
}
